### ISSUE TITLE
urltools does not parse google maps (and other) URLs correctly 

### ISSUE THREAD

**Issue by BernhardClemm** [schochastics/webtrackR#10]
I noticed this a while ago, and apparently this is known issue to the author, but not fixed/fixable. See the issues  https://github.com/Ironholds/urltools/issues/98
and 
https://github.com/Ironholds/urltools/issues/90

A workaround is possible with the `curlparse` package to extract the host, and then use urltools for splitting the host to get the domain. For example, the function I updated could then be

```
extract_domain <- function(wt){
  stopifnot("input is not a wt_dt object" = is.wt_dt(wt))
  vars_exist(wt,vars = "url")
  wt[,host:=curlparse::host(url)] #### this is the difference ####
  wt[,domain_name:=urltools::suffix_extract(host)$domain]
  wt[,suffix:=urltools::suffix_extract(host)$suffix]
  wt[,domain:=paste0(domain_name, '.', suffix)]
  wt[,c("domain_name", "suffix"):=NULL]
  wt[]
}
```
Downside would be that we'd rely on two packages, so not ideal.

**Comment by schochastics** [comment]
Thanks! Your PR does not include the `curlparse` command though. Did you find another workaround or is that a mistikae?

**Comment by BernhardClemm** [comment]
Well I did not use that workaround because I didn't want to introduce an additional library.

I am also not sure whether urltools might have some benefits that curlparse doesn't, so I was hesitant. What was the reason for you to go with urltools?

**Comment by schochastics** [comment]
Did a little bit of investigating. It appears that the issue only occurs when there is an "@" symbol in the url.
We can delete those for the domain extraction and that should "fix" the issue

**Comment by BernhardClemm** [comment]
Ok, this makes sense to me! Are you going to implement it or should I?

**Comment by schochastics** [comment]
you can do it in tour PR just do a new commit with the line above and I merge it
