### ISSUE TITLE
Check whether timestamp has right format in is.wt_dt?

### ISSUE THREAD

**Issue by BernhardClemm** [schochastics/webtrackR#13]
I am wondering whether it would be good to check whether timestamp is in posixct format when calling is.wt_dt(). Something like is(x$timestamp, "POSIXct").

Not sure whether it's necessary - as.wt_dt() seems to be the only way to create class wt_dt in the first place, and it has the conversion already.

**Comment by BernhardClemm** [comment]
hey @schochastics, nochmal hierzu eine Frage. Verstehe nicht 100%, was is.wt_dt machen soll. Wenn ich zum Beispiel folgendes mache: 
```
data("testdt_tracking")
wt <- as.wt_dt(testdt_tracking)
wt$url <- NULL
```
dann ist is.wt_dt immer noch TRUE. Aber ist das dann konzeptionell noch ein wt_dt? Anders gesagt, sind Anzahl und Typ der Variablen nicht auch das, was den dt_wt ausmacht?

**Comment by schochastics** [comment]
ne die klassen definition wt_dt sieht nur die basis variablen aus den webtrack daten vor. alles andere ist optional. Also solange die Standard Variablen da sind, ist es ein wt_dt objekt
