### ISSUE TITLE
test data too large

### ISSUE THREAD

**Issue by schochastics** [schochastics/webtrackR#20]
For the next submission, the test data size needs to be reduced
Currently, a warning is suppressed via `LazyDataCompression: bzip2` in DESCRIPTION

**Comment by BernhardClemm** [comment]
Other things test data should have:

- [ ] milliseconds
- [ ] duplicate visits

**Comment by BernhardClemm** [comment]
New version of classes data:

- [ ] one data set with hosts

**Comment by schochastics** [comment]
@BernhardClemm can this be closed now?

**Comment by BernhardClemm** [comment]
Can be closed as far as I am concerned
