### ISSUE TITLE
examples run too long

### ISSUE THREAD

**Issue by schochastics** [schochastics/webtrackR#21]
CRAN rules are <5 seconds. Relates to #20

**Comment by schochastics** [comment]
set to \dontrun for now to speedup checking

**Comment by schochastics** [comment]
looks better with new data except for `add_title` which we just keep on dontrun

**Comment by BernhardClemm** [comment]
I made the add_title example shorter, so you can check whether it's better now

**Comment by schochastics** [comment]
will leave this as dont run since it needs internet access
