### ISSUE TITLE
Make function descriptions/details/examples consistent across functions

### ISSUE THREAD

**Issue by BernhardClemm** [schochastics/webtrackR#26]

**Comment by BernhardClemm** [comment]
Updated descriptions/examples of (almost) all functions to make them consistent and easily understandable.

Left to do:

- for `isolation_index()`, it could be a bit clearer how connecting to web track data. Can we make it more general than conservative/liberal news consumption?
- description of `wt_dt`class: The sentence "These operations are applied on the data." is not very clear. 
- audience_incidence(), the description could be a bit more detailed.

**Comment by schochastics** [comment]
@BernhardClemm not sure how to make audience_incidence() more detailed, because IMO it describes what the function does well. What is unclear?

**Comment by BernhardClemm** [comment]
Not sure what I meant - fine as is.
