### ISSUE TITLE
Check why "setnames" needs data.table::

### ISSUE THREAD

**Issue by BernhardClemm** [schochastics/webtrackR#36]

**Comment by BernhardClemm** [comment]
Also check what's better:
```colnames(wt)[colnames(wt) == old_name] <- "new_name"```
or
```data.table::setnames(wt, "old_name", "new_name")

**Comment by schochastics** [comment]
always use setnames

**Comment by schochastics** [comment]
it wasnt part of any `@importFrom data.table` statement. If you wanna use functions without data.table::, they always need to occur in one of those
