### ISSUE TITLE
Find workaround for setnafill in drop_query

### ISSUE THREAD

**Issue by BernhardClemm** [schochastics/webtrackR#55]
function splits URL into components and then pastes together scheme, host and path. Before, it should turn NA to "". What is the most efficient way to do that?

See also https://stackoverflow.com/questions/7235657/fastest-way-to-replace-nas-in-a-large-data-table

**Comment by schochastics** [comment]
```r
wt[is.na(host), host := ""]
wt[is.na(path), path := ""]
```

maybe like this?
